---
title: "tidy_tuesday_12_27_2023"
author: "VP"
date: "2023-12-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#Load data
```{r}
library(tidytuesdayR)
library(tidyverse)
library(ggthemes)
library(RColorBrewer)
library(ggridges)
library(forcats)

alonedata <- tidytuesdayR::tt_load('2023-01-24')

survivalists <- alonedata$survivalists
loadouts <- alonedata$loadouts
episodes <- alonedata$episodes
seasons <- alonedata$seasons

head(survivalists)
head(loadouts)
head(episodes)
head(seasons)
```

#Cleaning
```{r}
#Partner duplicates
survivalists |> 
  mutate(name = recode(name, "Jim Baird" = "Jim & Ted Baird")) |> 
  mutate(name =recode(name, "Pete Brockdorff" = "Sam & Pete Brockdorff")) |> 
  filter(name != "Ted Baird" & name!= "Sam Brockdorff")-> survivalists

unique(survivalists$name)

loadouts |> 
  mutate(name = recode(name, "Jim Baird" = "Jim & Ted Baird")) |> 
  mutate(name =recode(name, "Pete Brockdorff" = "Sam & Pete Brockdorff")) |> 
  filter(name != "Ted Baird" & name!= "Sam Brockdorff")-> loadouts
```



#Quick Relationship Visualizations
```{r}
survivalists |> 
  ggplot(aes(x=days_lasted, y=age, color=gender))+ 
  geom_point(size=3, alpha= .8)+
  labs(title= "Age/Gender vs Days Lasted", x= "Days Lasted", y="Age", color= "Gender")+
  theme_classic()+
  scale_color_manual(values=c("#E09FDD","#547CE1"))+
  theme(plot.title= element_text(size=20),
        axis.text.x = element_text(size=13),
        axis.text.y = element_text(size=13),
        axis.title = element_text(size=15))



survivalists |> 
  group_by(gender) |> 
  ggplot(aes(x=days_lasted, y=gender, fill= gender))+ 
  geom_density_ridges()+
  labs(title= "Alone: Women survive longer than men on average", y= "", x=" Days Lasted", fill= "Gender")+
  theme_classic()+
  scale_fill_manual(values=c("#E09FDD","#547CE1"))

#First Place Winners

library(viridis)
survivalists |> 
  filter(result == 1) |> 
  select(season, name, days_lasted, gender) |> 
  ggplot(aes(x=fct_reorder(name, season), y=days_lasted, fill=days_lasted)) + geom_col()+
  labs(title= "Average Alone season winners last 75 days", x= "", y="Days Lasted", subtitle="Roland Welker of season 7 sets record with 100 day wilderness stint")+
  theme_classic()+
  guides(fill=FALSE)+
  theme(axis.text.x = element_text(angle = 35, vjust= .6))+
  scale_fill_viridis(begin=.1, end= .7)

?viridis

library(forcats)

loadouts |>
  count(item) |> 
  ggplot(aes(x=fct_reorder(item, n), y=n, fill=n)) +
  geom_col() +
  geom_text(aes(item, n + 3, label = n), size = 4) +
  coord_flip()+
  scale_fill_continuous(low = "#87BB9B", high = "#1C5432")+
  theme_classic()+
  labs(title= "Alone: Popular Loadout Items", y= "Count", x="")+
  guides(fill=FALSE)+
  theme(plot.title= element_text(size=20))

```

#Joining
```{r}
survivalists  |> 
  filter(name != c("Ted Baird","Sam Brockdorff")) |> 
  inner_join(loadouts, by=join_by(name, season)) ->surv_w_loadout


surv_w_loadout |> 
  mutate(winner = as.factor(case_when(result== "1"~ "Yes",
                            result!= "1"~ "No")))-> surv_w_loadout

surv_w_loadout |>
  count(item, winner) |> 
  ggplot(aes(x=fct_reorder(item, n), y=n, fill= winner, color=winner)) +
  geom_col() +
  coord_flip()+
  theme_classic()+
  labs(title= "Alone: What Items do Season Winners Bring?", y= "Count", x="", fill= "Season Winner")+
  theme(plot.title= element_text(size=20))+
  geom_text(aes(item, n + n, label = n), size = 4)+
  scale_fill_manual(values= c("#8D8D8D", "#32784D"))+
  scale_color_manual(values= c("white", "#18472A"))+
  guides(color=FALSE)

```




#Season vs Results
#Challenge: Inspired by @JacobCJameson
```{r}
library(ggrepel)
library(lubridate)
library(ggExtra)

episodes_small <- episodes %>%
  select(season, episode, imdb_rating, n_ratings)

survivalists_small <- survivalists %>%
  select(season, episode = result, days_lasted, name)

alonedata<- survivalists_small |> 
  left_join(episodes_small, by=join_by("season","episode"))

df_episodes_avg <-
  alonedata |>
  arrange(season, episode) |>
  mutate(episode_id = row_number()) |>
  group_by(season) |>
  mutate(
    avg = mean(days_lasted),
    episode_mod = episode_id + (9 * season), #Creating extra space between seasons
    mid = mean(episode_mod)) |>  #Want the next df_lines to plot in the middle 
  ungroup() |>
  mutate(season = factor(season))


df_lines <-
  df_episodes_avg |>
  group_by(season) |>
  summarize(
    start_x = min(episode_mod) - 5, #Placing lines on the modified episode numbers to center lines for each season
    end_x = max(episode_mod) + 5,
    y = unique(avg) ) |>
  pivot_longer(
    cols = c(start_x, end_x),
    names_to = "type",
    values_to = "x") |>
  mutate(
    x_group = if_else(type == "start_x", x + .1, x - .1),
    x_group = if_else(type == "start_x" & x == min(x), x_group - .1, x_group),
    x_group = if_else(type == "end_x" & x == max(x), x_group + .1, x_group))

plot <- df_episodes_avg |> 
  ggplot(aes(x= episode_mod, y=days_lasted)) + 
  geom_segment(
    aes(
      xend = episode_mod,
      yend = avg, 
      color = season)) #Adding segments for time lasted 


plot <- plot + 
  geom_line(data = df_lines, #Creating line that connects season to next season
    aes(x=x, y=y),
    color = "grey40") +
  geom_line(data = df_lines, #Adding lines of avg time lasted per season
    aes(x=x_group, y=y, color = season),size = 3.5) + 
  geom_point(aes(color = season)) #adding points for lollipop

library(showtext)

#Adding Season labels to mid point of each season
plot <- plot + 
  geom_label(
    aes(x=mid, y=-10.20,label = glue::glue(" SEASON {season} "),color = season),
    size = 5,
    fill = NA,
    family = "Pragati Narrow",
    fontface = "bold",
    label.padding = unit(.5, "lines"),
    label.r = unit(.25, "lines"), 
    label.size = NA
  ) 

plot <- plot + 
  scale_y_continuous(limits = c(-15, 110),breaks = seq(0, 100, by = 20)) +
  scale_color_manual(
    values = c("#B6AE84", "#8D8D8D", "#4E8572", "#6D684E", "#86CBB3",
               "#D3CBA3", "#1D5F48", "#A6A7A7", "#58533C"),
    guide = FALSE ) +
  labs(caption= str_wrap("Data comes from the TV series Alone, 
                         collected and shared by Dan Oehm. Visualization inspired by @JacobCJameson", 200),
       subtitle= "A Season-by-Season Breakdown of ALONE Contestant Longevity",
       title="SURVIVING SOLITUDE",
       y = 'Days Survived', x= "") +
  guides(
    size = guide_bins(
      show.limits = TRUE,
      direction = "horizontal",
      title.position = "top",
      title.hjust = .5)) +
  geom_label(aes(x=129,y=100, label = "Roland Welker survived 100 days"), size=5,
             hjust = 0, vjust = "inward",
             nudge_x = 0.05, nudge_y = 2,
             label.padding = unit(0.2, "lines"),
             label.size = NA, color='#4E8572') +
  theme_classic()+
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        plot.title = element_text(size=20, face= "bold"))
plot


```

